[package]
name = "quinn_test"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = "0.10.2"
quinn-proto = "0.10.2"
tokio = { version = "1.33.0", features = ["full", "macros"] }
rustls = "0.21.7"
rustls-pemfile = "1.0.3"
rcgen = "0.11.3"
futures = "0.3.30"
futures-timer = "3.0.3"